-- H2 2.1.214; 
;              
CREATE USER IF NOT EXISTS "SA" SALT '2d983dad526e97df' HASH '193f6f5a906464016a61057a9ee871bf37ded77c5c87b409f9a13f508c362c8b' ADMIN;          
CREATE SEQUENCE "PUBLIC"."SEQUENCE_ON_TASK" START WITH 1;      
CREATE SEQUENCE "PUBLIC"."SEQUENCE_ON_TODO_USER" START WITH 1; 
CREATE MEMORY TABLE "PUBLIC"."TASK"(
    "ID" BIGINT NOT NULL,
    "COMMENTS" CHARACTER VARYING(255),
    "CREATED_AT" DATE,
    "LARGE_DESC" CHARACTER VARYING(255),
    "SCHEDULE_TYPE" CHARACTER VARYING(255),
    "SHORT_DESC" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255),
    "TIMING" DATE,
    "UPDATED_AT" DATE,
    "CREATED_BY" BIGINT
);           
ALTER TABLE "PUBLIC"."TASK" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TASK;     
CREATE MEMORY TABLE "PUBLIC"."TODO_USER"(
    "ID" BIGINT NOT NULL,
    "ADDR_LINE" CHARACTER VARYING(255),
    "CITY" CHARACTER VARYING(255),
    "CONTACT_NUMBER" CHARACTER VARYING(255),
    "COUNTRY" CHARACTER VARYING(255),
    "CREATED_AT" DATE,
    "EMAIL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PINCODE" CHARACTER VARYING(255),
    "STATE" CHARACTER VARYING(255),
    "TYPE" CHARACTER VARYING(255),
    "UPDATED_AT" DATE
);          
ALTER TABLE "PUBLIC"."TODO_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TODO_USER;
ALTER TABLE "PUBLIC"."TASK" ADD CONSTRAINT "PUBLIC"."FKK1C3TSSE6BMP0OLFU5MQRXYAM" FOREIGN KEY("CREATED_BY") REFERENCES "PUBLIC"."TODO_USER"("ID") NOCHECK;     
